hihome.in/helloworld/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "TalentPoint"
admin.site.site_title = "TalentPoint Admin Panel"
admin.site.index_title = "Welcome to TalentPoint Admin Panel"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace="fileapp")),
    
    
    
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hihome.in/home/urls.py
from django.contrib import admin
from django.urls import path
from home import views
app_name = "fileapp"
urlpatterns = [
    path('',views.index,name='home'),
    path('about',views.about,name='aboutus'),
    path('contactus',views.contactus,name='contactus'),
    path('upcomming',views.upcomming,name='upcomming'),
    path('signup',views.signup,name='signup'),
    path('login',views.handleLogin,name='handleLogin'),
    path('handleLogout',views.handleLogout,name='hangleLogout'),
    path('registration',views.registration,name='registration'),
    path('comp1',views.comp1,name='comp1'),
    path('upload',views.send_files,name="upload"),
    
    
]

hihome.in/home/models.py
# from typing_extensions import Required
from django.db import models

# Create your models here.
class Registration(models.Model):
    name = models.CharField(max_length=100,null=False)
    lastname = models.CharField(max_length=100)
    email =models.CharField(max_length=100)
    phone = models.CharField(max_length=12)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=20)
    competetions = models.CharField(max_length=30)
    zip =models.CharField(max_length=10)
    date = models.DateField()
    
    def __str__(self):
        return self.name

class Contactus(models.Model):
    contactName = models.CharField(max_length=100)
    contactEmail = models.CharField(max_length=100)
    contactMessage = models.TextField()
    def __str__(self):
        return self.contactName

class myuploadfile(models.Model):
    f_name = models.CharField(max_length=100,default="")
    myfile = models.FileField(upload_to="")
    def __str__(self) :
        return self.f_name

hihome.in/home/views.py
from django.shortcuts import render,HttpResponse,redirect
from datetime import datetime
from home.models import Registration,Contactus,myuploadfile
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login, logout


def index(request):
    return render(request,'index.html')


def about(request):
    return render(request,'about.html')

def upcomming(request):
    return render(request,'upcomming.html')

    



def contactus(request):
    if request.method == "POST":
        contactName = request.POST.get('contactName')
        contactEmail = request.POST.get('contactEmail')
        contactMessage = request.POST.get('contactMessage')
        contactus = Contactus(contactName=contactName,contactEmail=contactEmail,contactMessage=contactMessage)
        contactus.save()
        messages.success(request,'Message sent successfully ! Thanks for contacting us ...')
    return render(request,'contactus.html')



def registration(request):
    if request.method == "POST" :
        
        
        name = request.POST.get('name')
        lastname = request.POST.get('lastname')
        email = request.POST.get('email')
        address = request.POST.get('address')
        city = request.POST.get('city')
        state = request.POST.get('state')
        phone = request.POST.get('phone')
        competetions = request.POST.get('competetions')
        zip = request.POST.get('zip')
        
        registration = Registration(name=name,phone=phone,lastname=lastname,email=email,address=address,city=city,state=state,zip=zip,competetions=competetions,date=datetime.today())
        registration.save()
        
     
        return redirect('/upload')
    
    return render(request,'registration.html')

def signup(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        confirm_password = request.POST['confirm_password']
        if pass1==confirm_password:
            myuser = User.objects.create_user(username,email,pass1)
            myuser.save()
            messages.success(request,"New account is created Login Now !")
            return redirect('/')
            
        else:
            messages.success(request,"Password not matched , try again !")
            
    return render(request,'signup.html')

    #else:
        # return HttpResponse('404 - Not Found')

def handleLogin(request):
    if request.method == "POST":
        loginUsername = request.POST['loginUsername']
        loginPassword = request.POST['loginPassword']

        user = authenticate(username=loginUsername,password=loginPassword)

        if user is not None:
            login(request,user)
           
            messages.success(request,f"Welcome {request.user}, You successfully logged in !")
            return redirect('/')
        else:
            messages.error(request,"Invalid Username or Password, Please try again !")
            return redirect('/')

        return HttpResponse('handleLogin')

def handleLogout(request):
    
    logout(request)
    messages.success(request,"Successfully Logged Out !")
    return redirect('/')
    
def comp1(request):
    return render(request,'comp1.html')
    

def send_files(request):
    if request.method == "POST":
        f_name = request.POST.get("filename")
        myfile = request.FILES.getlist("uploadFiles")
        
        for i in myfile:
            myuploadfile(myfile=i,f_name=f_name).save()
            messages.success(request,"File Uploaded !")
        
    return render(request,'send_files.html')

hihome.in/templates/about.html
{% extends 'base.html' %}
{% block title %}About us | {% endblock title %}
{% block body %}
THis is about block body
{% endblock body %}

hihome.in/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <title>{% block title %}{% endblock title %}hihome</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" type="image/jpg" href="static/favicon_io/favicon.png"/>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Bungee Inline' rel='stylesheet'>

  <style>
    body {
      font-family: "Lato", sans-serif;



      /* Create the parallax scrolling effect */
      background-attachment: fixed;
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
    }

    .sidenav {
      height: 100%;
      width: 0;
      position: fixed;
      z-index: 1;
      top: 0;
      left: 0;
      background-color: #111;
      overflow-x: hidden;
      transition: 0.5s;
      padding-top: 60px;
    }

    .sidenav a {
      padding: 8px 8px 8px 32px;
      text-decoration: none;
      font-size: 25px;
      color: #818181;
      display: block;
      transition: 0.3s;
    }

    .sidenav a:hover {
      color: #f1f1f1;
    }

    .sidenav .closebtn {
      position: absolute;
      top: 0;
      right: 25px;
      font-size: 36px;
      margin-left: 50px;
    }

    @media screen and (max-height: 450px) {
      .sidenav {
        padding-top: 15px;
      }

      .sidenav a {
        font-size: 18px;
      }
    }

    /* dropdown in the sidebar */
    /* On mouse-over */
    .sidenav a:hover,
    .dropdown-btn:hover {
      color: #f1f1f1;
    }

    /* Main content */
    .main {
      margin-left: 200px;
      /* Same as the width of the sidenav */
      font-size: 20px;
      /* Increased text to enable scrolling */
      padding: 0px 10px;
    }

    /* Add an active class to the active dropdown button */
    .active {
      background-color: green;
      color: white;
    }

    /* Dropdown container (hidden by default). Optional: add a lighter background color and some left padding to change the design of the dropdown content */
    .dropdown-container {
      display: none;
      background-color: #262626;
      padding-left: 8px;
    }

    /* Optional: Style the caret down icon */
    .fa-caret-down {
      float: right;
      padding-right: 8px;
    }

    /* Some media queries for responsiveness */
    @media screen and (max-height: 450px) {
      .sidenav {
        padding-top: 15px;
      }

      .sidenav a {
        font-size: 18px;
      }
    }

    /* Footer section */

    footer {

      left: 0;
      bottom: 0;
      width: 100%;
      background-color: black;
      color: white;
      text-align: center;
      bottom: 0;
    }

    /* login */
    body {
      font-family: Arial, Helvetica, sans-serif;
    }

    /* Full-width input fields */
    input[type=text],
    input[type=password] {
      width: 100%;
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      box-sizing: border-box;
    }

    /* Set a style for all buttons 
    button {
      background-color: #4CAF50;
      color: white;
      padding: 14px 20px;
      margin: 8px 0;
      border: none;
      cursor: pointer;
      width: 20mm;*/


    

    button:hover {
      opacity: 0.8;
    }

    /* Extra styles for the cancel button */
    .cancelbtn {
      width: auto;
      padding: 0px 5px;
      background-color: #f44336;
    }

    /* Center the image and position the close button */
    .imgcontainer {
      text-align: center;
      margin: 24px 0 12px 0;
      position: relative;
    }

    img.avatar {
      width: 40%;
      border-radius: 50%;
    }

    .container {
      padding: 16px;
    }

    /* span.psw {
      float: right;
      padding-top: 16px;
      padding: 10px
    } */

    /* The Modal (background) */
    .modal {
      display: none;
      /* Hidden by default */
      position: fixed;
      /* Stay in place */
      z-index: 1;
      /* Sit on top */
      left: 0;
      top: 0;
      width: 100%;
      /* Full width */
      height: 100%;
      /* Full height */
      overflow: auto;
      /* Enable scroll if needed */
      background-color: rgb(0, 0, 0);
      /* Fallback color */
      background-color: rgba(0, 0, 0, 0.4);
      /* Black w/ opacity */
      padding-top: 60px;
    }

    /* Modal Content/Box */
    .modal-content {
      background-color: #fefefe;
      margin: 5% auto 15% auto;
      /* 5% from the top, 15% from the bottom and centered */
      border: 1px solid #888;
      width: 80%;
      /* Could be more or less, depending on screen size */
    }

    /* The Close Button (x) */
    .close {
      position: absolute;
      right: 25px;
      top: 0;
      color: #000;
      font-size: 35px;
      font-weight: bold;
    }

    .close:hover,
    .close:focus {
      color: red;
      cursor: pointer;
    }

    /* Add Zoom Animation */
    .animate {
      -webkit-animation: animatezoom 0.6s;
      animation: animatezoom 0.6s
    }

    @-webkit-keyframes animatezoom {
      from {
        -webkit-transform: scale(0)
      }

      to {
        -webkit-transform: scale(1)
      }
    }

    @keyframes animatezoom {
      from {
        transform: scale(0)
      }

      to {
        transform: scale(1)
      }
    }

    /* Change styles for span and cancel button on extra small screens */
    @media screen and (max-width: 300px) {
      span.psw {
        display: block;
        float: none;
      }

      .cancelbtn {
        width: 100%;
      }
    }

    .container {
      width: 900;
      height: 900;
    }
  </style>


</head>

<body>


  <nav class="navbar navbar-expand-lg navbar-light bg-dark" style="height: 52px;">
    <ul class="navbar-nav mr-auto" style="display: inline;"></ul>
    <li class="">
      <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <img src="static/favicon_io/nav2.png" alt="" style="margin-left: 30px;">
        <a href="/">Home</a>
        <!-- <a href="/about">About us</a> -->
        <a href="/contactus">Contact us</a>
        <a href="/upcomming">Events</a>
        <a class="dropdown-btn">Results<i class="fa fa-caret-down"></i></a>
        <div class="dropdown-container">
          <a href="static/commingsoon.jpeg">April 2021</a>
          <a href="static/commingsoon.jpeg">May 2021</a>
          <a href="static/commingsoon.jpeg">June 2021</a>
        </div>
        {% if user.is_authenticated %}
        <div style="padding-left: 50px;padding-top:95px">
        
        <a href="/handleLogout"><button  class="btn btn-outline-success my-2 my-sm-0"style="color:white;background-color:green" >Logout</button></a></div>
        {% else %}
        <div style="padding-left: 95px;padding-top:95px">
          <button class="btn btn-outline-success my-2 my-sm-0"
            onclick="document.getElementById('id01').style.display='block'"
            style="color:white;background-color:green">Login</button></div> {% endif %}
          <div id="id01" class="modal">

            <form class="modal-content animate" action="/login" method="post">
              <div class="imgcontainer">
                <span onclick="document.getElementById('id01').style.display='none'" class="close"
                  title="Close Modal">&times;</span>
                <img src="static/login.png" alt="Avatar" class="avatar">
              </div>

              <div class="container">
                <label for="uname"><b>Username</b></label>
                <input type="text" placeholder="Enter Username" name="loginUsername" required>

                <label for="psw"><b>Password</b></label>
                <input type="password" placeholder="Enter Password" name="loginPassword" required>
                {% csrf_token %}
               
                <button type="submit" class="btn btn-outline-success my-2 my-sm-0" style="color: white;background-color: green;">Login</button>
               
                
               
                <label>
                  <input type="checkbox" checked="checked" name="remember"> Remember me
                </label>

              </div>

              <div class="container" style="background-color:#f1f1f1;position: relative;margin-top: -20px;">
                <button type="button" onclick="document.getElementById('id01').style.display='none'"class="btn btn-outline-success my-2 my-sm-0" style="background-color:red;color: white;">Cancel</button>
              <a href="/signup" class="btn btn-primary" style="color:white;">Signup</a>
              </div>
              
              </div>
            </form>
          </div>
        </div>

      </div>
    </li>
    <li style="position: absolute;padding-left: 25px;font-size: 35px;">
      
      <label style="color:white; font-family:Bungee Inline">Hihome!</label>

    </li>



  </nav>
 
  {% if messages %}
  {% for message in messages %}
  <div id = "alert"class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" >
  {{ message }}
  
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>

  {% endfor %}
  {% endif %}


  <span style="font-size:30px;cursor:pointer;position: absolute;top: 1mm;color: white;padding-left: 15px;"
    onclick="openNav()">&#9776</span>
  <script>
    function openNav() {
      document.getElementById("mySidenav").style.width = "250px";
      document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
    }

    function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
      document.body.style.backgroundColor = "white";
    }
    var dropdown = document.getElementsByClassName("dropdown-btn");
    var i;
    // Dropdown sidebar
    for (i = 0; i < dropdown.length; i++) {
      dropdown[i].addEventListener("click", function () {
        this.classList.toggle("active");
        var dropdownContent = this.nextElementSibling;
        if (dropdownContent.style.display === "block") {
          dropdownContent.style.display = "none";
        } else {
          dropdownContent.style.display = "block";
        }
      });
    }
    // login------------------------------------
    // Get the modal
    var modal = document.getElementById('id01');

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    }

  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
    crossorigin="anonymous"></script>


  {% block body %}{% endblock body %}


  <!-- Footer -->
  <footer class="page-footer font-small special-color-dark pt-4">

    <!-- Footer Elements -->
    <div class="container">

      <!-- Social buttons -->
      <ul class="list-unstyled list-inline text-center">
        <li class="list-inline-item">
         <img src="static/facebook.png" alt="">
        </li>
        <li class="list-inline-item">
          <img src="static/insta.png" alt="">
        </li>
        <li class="list-inline-item">
          <img src="static/tweeter.png" alt="">
        </li>
        
      
      </ul>
    <div class="footer-copyright text-center py-3">© 2021 Talent Point

    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->

</body>

</html>

hihome.in/templates/comp1.html
{% extends 'base.html' %}
{% block title %}News | {% endblock title %}
{% block body %}
<div class="card" style="align-self: center;">
<img src="static/comp1.jpg" class="card-img-top" alt="...">
<div class="card-body">
    <h5 class="card-title">Vocal For Local...</h5>
    <p class="card-text">"Methods to developing your local areas"</p>
    <p> Details
    Question Problem :
    India is the developing country , yet not developed . Due to hard times of this Corona Pandamic
    Our local areas and market is degrading day by day. This is the right time to protect the environment 
    because ...
    <a href="/registration" class="btn btn-primary">Register</a>
</div>
</div>
{% endblock body %}

hihome.in/templates/contactus.html
{% extends 'base.html' %}
{% block title %}Contact us | {% endblock title %}
{% block body %}

<style>
* {
  box-sizing: border-box;
}

/* Style inputs */
input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

/* Style the container/contact section */
.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}

/* Create two columns that float next to eachother */
.column {
  float: left;
  width: 50%;
  margin-top: 6px;
  padding: 20px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .column, input[type=submit] {
    width: 100%;
    margin-top: 0;
  }
}
#Send{
    background-color:green;
    color: white;
}
</style>



<div class="container">
  <div style="text-align:center">
    <h2>Contact Us</h2>
    <p>We are there 24 X 7 , for you :</p>
  </div>
  <div class="row">
    <div class="column">
      <img src="static/mail.jpg" style="width:100%">
    </div>
    <div class="column">
      <form action="/contactus" method="post">
        <label for="fname">Name</label>
        <input type="text" id="fname" name="contactName" placeholder="Enter Your name" required>
        <label for="email">Email</label>
        <input type="text" id="email" name="contactEmail" placeholder="Enter Your Email address" required>
        <label for="subject">Message</label>
        <textarea id="subject" name="contactMessage" placeholder="Write your query here ..." style="height:170px" required></textarea>
        {% csrf_token %}
        <button id="Send"type="submit">Send</button>
      </form>
    </div>
  </div>
</div>
<br>
<br>
{% endblock body %}

hihome.in/templates/index.html
{% extends 'base.html' %}
{% block title %}Home | {% endblock title %}
{% block body %}



<div class='container-fluid my-4'>
  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <!-- <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
        aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
        aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
        aria-label="Slide 3"></button>
    </div> -->
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="static/comp1.jpg" class=" d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="static/commingsoon.jpeg" class=" d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="static/commingsoon.jpeg" class="d-block w-100" alt="...">
      </div>
    </div>
  </div>

</div>
<div id="h3" style="text-align:center;padding: 5mm;">
  <h3>
    Arriving MindStroms...
  </h3>
</div>

<div class="card">
  <div class="card" style="align-self: center; padding-left: 4cm; padding-top: 5mm;">
    <a href="/comp1">
    <img src="static/comp1.jpg" class="card-img-top" alt="...">
    </a>
    <div class="card-body">
      <h5 class="card-title">Vocal For Local...</h5>
      <p class="card-text">"Methods to develop your local areas"</p>

      {% if user.is_authenticated %}
      <a href="/registration" class="btn btn-primary">Register</a>
      {% else %}
       
        <button class="btn btn-primary"
            onclick="document.getElementById('id01').style.display='block'">Register</button> 
      {%endif%}
      
    </div>
  </div>
  
  <br>

  <div class="card">
    <div class="card" style="align-self: center; padding-right: 5cm; padding-top: 5mm;">
      <img src="static/commingsoon.jpeg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Programming</h5>
        <p class="card-text">This is the Programming competetion.</p>
        <a href="/static/commingsoon.jpeg" class="btn btn-primary">Register</a>
      </div>
    </div>
    <br>

    <div class="card">
      <div class="card" style="align-self: center; padding-left: 5cm; padding-top: mm; padding-bottom: 5cm;">
        <img src="static/commingsoon.jpeg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Photography...</h5>
          <p class="card-text">This is the photography competetion.</p>
          <a href="/static/commingsoon.jpeg" class="btn btn-primary">Register</a>
        </div>
      </div>

    </div>
    <br>
{% endblock body %}

hihome.in/templates/news.html
{% extends 'base.html' %}
{% block title %}News | {% endblock title %}
{% block body %}
THis is News block body
{% endblock body %}

hihome.in/templates/register.html
{% extends 'base.html' %}
{% block title %}Home | {% endblock title %}
{% block body %}
<p>
this is register page
</p>
{% endblock body %}

hihome.in/templates/registration.html
{% extends 'base.html' %}
{% block title %}Home | {% endblock title %}
{% block body %}


{% comment %} <ul class="messages">
      <li
   class="{{ message.tags }}"{% endif %}></li>
       
</ul> {% endcomment %}
{% comment %} {% if message.tags %} {% endcomment %}
<style>
#alert{
    text-align:center;

}
</style>
 


<div class="container">
    <form  method="POST">{% csrf_token %}
        
        <div class="row g-3">
            <div class="col">
                <label for="name"  class="form-label">Name</label>
                <input type="name" name="name" class="form-control" id="name" placeholder="First name" aria-label="First name" required>
            </div>
            <div class="col">
                <label for="lastname" class="form-label">Last name</label>
                <input type="lastname" name="lastname" class="form-control" id="lastname"placeholder="Last name" aria-label="Last name" required>
            </div>
        </div>
        <div class="row g-3">
            <div class="col">
                <div class="row g-3">
                    <div class="col">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" name="email" class="form-control" id="email" required>
                    </div>
                    <div class="col">
                        <label for="Phone" class="form-label">Phone number</label>
                        <input type="phone" name="phone"class="form-control" id = "phone"placeholder="Phone number" aria-label="Last name" required>
                    </div>
                </div>

            </div>

        </div>


        <div class="col-12">
            <label for="address" class="form-label">Address</label>
            <input type="address" name="address"class="form-control" id="address"
                placeholder="such as: street,nearby,ward no.,home no." required>
        </div>
        <div class="col-md-6">
            <label for="city" class="form-label">City</label>
            <input type="city" name="city"class="form-control" id="city" required>
        </div>
        <div class="col-md-4">
            <label for="state" class="form-label">State</label>
            <select id="state" name="state"class="form-select">
                <option selected>Choose...</option>
                <option>Assam</option>
                <option>Bihar</option>
                <option>Chhattisgarh</option>
                <option>Goa</option>
                <option>Gujarat</option>
                <option>Haryana</option>
                <option>Himachal Pradesh</option>
                <option>Jharkhand</option>
                <option>Karnataka</option>
                <option>Kerala</option>
                <option>Madhya Pradesh</option>
                <option>Maharashtra</option>
                <option>Manipur</option>
                <option>Meghalaya</option>
                <option>Mizoram</option>
                <option>Nagaland</option>
                <option>Odisha</option>
                <option>Punjab</option>
                <option>Sikkim</option>
                <option>Tamil Nadu</option>
                <option>Telangana</option>
                <option>Tripura</option>
                <option>Uttar Pradesh</option>
                <option>Uttarakhand</option>
                <option>West Bengal</option>

            </select>
        </div>
        <div class="col-md-2">
            <label for="zip" class="form-label">Zip</label>
            <input type="zip" name="zip"class="form-control" id="zip" required>
        </div> 


        <div class="col-md-4">
            <label for="competetions" class="form-label">Competetions</label>
            <select id="competetions" name="competetions"class="form-select">
                <option selected>Choose...</option>
                <option>VocalForLocal</option>
                <!-- <option></option>
                <option></option>
                <option></option> -->
            </select>
            <br>
            
            <Br>


            <div class="col-12">
                <button type="submit" class="btn btn-primary"> NEXT </button>
            </div>
            <br>


    </form>

</div>
{% endblock body %}

hihome.in/templates/send_files.html
{% extends 'base.html' %}
{% block title %}Home | {% endblock title %}
{% block body %}
    <div id="img">
    <img src="/static/uploading.jpg" alt="" style="padding-left: 75px;">
    </div>
    </div>
    <form action="{% url 'fileapp:upload' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <input type="text" placeholder="Your Name" name="filename" required>
        <input type="file" mutliple name = "uploadFiles" required>
        <label for="payment">Registration Fee 100</label>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock body %}

hihome.in/templates/upcomming.html
{% extends 'base.html' %}
{% block title %}Events | {% endblock title %}
{% block body %}
<h1 style="text-align:center;padding-top:5mm">Events</h1>
<div>
<div class="card">
  <div class="card" style="">
    <img src="https://source.unsplash.com/WLUHO9A_xik/500x300" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Vocal For Local...</h5>
      
    </div>
  </div>
<div class="card">
  <div class="card" style="">
    <img src="https://source.unsplash.com/WLUHO9A_xik/500x300" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Photography...</h5>
      <p class="card-text">This is the photography competetion.</p>
      
    </div>
  </div>
</div>
<div class="card">
  <div class="card" style="">
    <img src="https://source.unsplash.com/WLUHO9A_xik/500x300" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Photography...</h5>
      <p class="card-text">This is the photography competetion.</p>
      
    </div>
  </div>
{% endblock body %}